apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-telnet-curl-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ssnaan/kube-telnet-curl-backend  
        ports:
        - containerPort: 8000  
