apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-telnet-curl-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ssnaan/kube-telnet-curl-frontend
        ports:
        - containerPort: 5000
